# system
mode: 0
distribute: True
num_parallel_workers: 8

# dataset
dataset: "imagenet"
data_dir: "/path/to/imagenet"
shuffle: True
dataset_download: False
batch_size: 64
drop_remainder: True

# augmentation
scale: [0.67, 1.0]
ratio: [0.75, 1.333]
hflip: 0.5

# model
model: "simmim_swin_4_192_pretrain"
drop_rate: 0.0
drop_path_rate: 0.0
pretrained: False
ckpt_path: ""
keep_checkpoint_max: 10
ckpt_save_dir: "./ckpt"
epoch_size: 100
dataset_sink_mode: False
amp_level: "O0"
clip_grad: True
clip_value: 5.0

# loss
loss: "None"

# lr scheduler
scheduler: "warmup_cosine_decay"
lr: 2e-4
warmup_epochs: 10
warmup_factor: 5e-3
min_lr: 1e-5
decay_epochs: 90
lr_epoch_stair: False

# optimizer
opt: "adamw"
weight_decay: 0.05
filter_bias_and_bn: True
use_nesterov: False

# pre-train
pretrain_resize: [192]
pretrain_interpolations: ["bicubic"]
mask_type: "patch_aligned"
mask_ratio: 0.6
mask_patch_size: 32
